version: "2.4"

networks:
  go-pb_dev:
    external: false

volumes:
  postgres-data-dev:

services:
###############################################################################
# Postgres database server.
# The ./services/db-server/db-healthcheck.sh script is used by Docker to
# determine the health status of the running container. This is important
# because in the depended services you can specify "service_healthy" condition
# which will make sure that the database is up and running.
  db-server:
    image: postgres:13-alpine
    container_name: db-server
    restart: unless-stopped
    networks:
      - go-pb_dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./scripts/db-healthcheck.sh:/db-healthcheck.sh
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=iliaf
      - POSTGRES_PASSWORD=iliaf
      - POSTGRES_DB=iliaf
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432  
    healthcheck:
      test: ["CMD", "/db-healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    container_name: db-admin
    depends_on:
      db-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - go-pb_dev
    ports:
      - 8888:8080

  # app:
  #   image: iliafrenkel/go-pb:latest
  #   container_name: app
  #   depends_on:
  #     db-server:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   networks:
  #     - go-pb_dev
  #   environment:
  #     - GOPB_API_DB_CONN_STRING=host=db-server user=iliaf password=iliaf dbname=iliaf port=5432 sslmode=disable
  #     - GOPB_WEB_LOGO=bighead.svg
  #     - GOPB_WEB_HOST=0.0.0.0
  #     - GOPB_API_TOKEN_SECRET=very#secret#api#token#donotshare
  #     - GOPB_WEB_COOKIE_AUTH_KEY=verysecretcookieauthkeydontshare
  #   ports:
  #     - 8080:8080
##
###############################################################################
