# Can be run with Podman via:
# podman play kube podman-kube.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-healthcheck-script
data:
  db-healthcheck.sh: |
    #!/bin/bash
    set -eo pipefail

    host="$(hostname -i || echo '127.0.0.1')"
    user="${POSTGRES_USER:-postgres}"
    db="${POSTGRES_DB:-$POSTGRES_USER}"
    export PGPASSWORD="${POSTGRES_PASSWORD:-}"

    args=(
        # force postgres to not use the local unix socket (test "external" connectibility)
        --host "$host"
        --username "$user"
        --dbname "$db"
        --quiet --no-align --tuples-only
    )

    if select="$(echo 'SELECT 1' | psql "${args[@]}")" && [ "$select" = '1' ]; then
        exit 0
    fi

    exit 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: go-pb-pod
  labels:
    app: go-pb
spec:
  restartPolicy: Never
  containers:
    - name: db-server
      image: postgres:18-alpine
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_USER
          value: ${DB_USER}
        - name: POSTGRES_PASSWORD
          value: ${DP_PASSWORD}
        - name: POSTGRES_DB
          value: ${DB_NAME}
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
        - name: db-healthcheck
          mountPath: /db-healthcheck.sh
          subPath: db-healthcheck.sh
      livenessProbe:
        exec:
          command:
            - /db-healthcheck.sh
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 5
    - name: app
      image: ghcr.io/iliafrenkel/go-pb:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
      env:
        - name: GOPB_API_DB_CONN_STRING
          value: ${GOPB_API_DB_CONN_STRING}
        - name: GOPB_WEB_LOGO
          value: ${GOPB_WEB_LOGO}
        - name: GOPB_WEB_HOST
          value: ${GOPB_WEB_HOST}
        - name: GOPB_API_TOKEN_SECRET
          value: ${GOPB_API_TOKEN_SECRET}
        - name: GOPB_WEB_COOKIE_AUTH_KEY
          value: ${GOPB_WEB_COOKIE_AUTH_KEY}
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data-dev
    - name: db-healthcheck
      configMap:
        name: db-healthcheck-script
        defaultMode: 0755
